import {
    Flex,
    Button,
} from '@chakra-ui/react'

export default function CalculatorPad() {
    return (
        <Flex
            h="65%"
            w="100%"
            direction="column"
            p="4px"
            gap="2px"
            color="#f8e4e3"
        >
            <Flex
                h="100%"
                w="100%"
                gap="2px"
                justify="spaced-between"
                align="center"
            >
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    %
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    CE
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    C
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    Backspace
                </Button>
            </Flex>
            <Flex
                h="100%"
                w="100%"
                gap="2px"
                justify="spaced-between"
                align="center"
            >
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    1/x
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    x²
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    Sqrrt(x)
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    /
                </Button>
            </Flex>
            <Flex
                h="100%"
                w="100%"
                gap="2px"
                justify="spaced-between"
                align="center"
            >
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    7
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    8
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    9
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    X
                </Button>
            </Flex>
            <Flex
                h="100%"
                w="100%"
                gap="2px"
                justify="spaced-between"
                align="center"
            >
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    4
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    5
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    6
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    -
                </Button>
            </Flex>
            <Flex
                h="100%"
                w="100%"
                gap="2px"
                justify="spaced-between"
                align="center"
            >
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    1
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    2
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    3
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#323232"
                    _hover={{
                        backgroundColor: "#3c3c3c",
                    }}
                >
                    +
                </Button>
            </Flex>
            <Flex
                h="100%"
                w="100%"
                gap="2px"
                justify="spaced-between"
                align="center"
            >
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    +/-
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    0
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    bgColor="#3c3c3c"
                    _hover={{
                        backgroundColor: "#323232",
                    }}
                >
                    ,
                </Button>
                <Button
                    h="100%"
                    w="100%"
                    color="#3c3c3c"
                    bgColor="#4CC2FF"
                >
                    =
                </Button>
            </Flex>
        </Flex>
    )
}